musker/urls.py
from django.urls import path
from . import views


app_name ='musker'

urlpatterns = [
    path('', views.home, name="home"),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('profile/followers/<int:pk>', views.followers, name='followers'),
    path('profile/follows/<int:pk>', views.follows, name='follows'),
    path('login/', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_user/', views.update_user, name='update_user'),
    path('meep_like/<int:pk>', views.meep_like, name="meep_like"),
    path('meep_show/<int:pk>', views.meep_show, name="meep_show"),
    path('unfollow/<int:pk>', views.unfollow, name="unfollow"),
    path('follow/<int:pk>', views.follow, name="follow"),
    path('delete_meep/<int:pk>', views.delete_meep, name="delete_meep"),
    path('edit_meep/<int:pk>', views.edit_meep, name="edit_meep"),
    path('search/', views.search, name='search'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musker.urls',namespace='musker')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# create meep model
class Meep(models.Model):
	user = models.ForeignKey(
		User, related_name="meeps", 
		on_delete=models.DO_NOTHING
		)
	body = models.CharField(max_length=200)
	created_at = models.DateTimeField(auto_now_add=True)
	likes = models.ManyToManyField(User, related_name="meep_like", blank=True)


	# Keep track or count of likes
	def number_of_likes(self):
		return self.likes.count()



	def __str__(self):
		return(
			f"{self.user} "
			f"({self.created_at:%Y-%m-%d %H:%M}): "
			f"{self.body}..."
			)


# Create A User Profile Model
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	follows = models.ManyToManyField("self", 
		related_name="followed_by",
		symmetrical=False,
		blank=True)	
	
	date_modified = models.DateTimeField(User, auto_now=True)	
	profile_image = models.ImageField(null=True, blank=True, upload_to="images/")
	
	profile_bio = models.CharField(null=True, blank=True, max_length=500)
	homepage_link = models.CharField(null=True, blank=True, max_length=100)
	facebook_link = models.CharField(null=True, blank=True, max_length=100)
	instagram_link = models.CharField(null=True, blank=True, max_length=100) 
	linkedin_link = models.CharField(null=True, blank=True, max_length=100)
	
	def __str__(self):
		return self.user.username

# Create Profile When New User Signs Up
#@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
	if created:
		user_profile = Profile(user=instance)
		user_profile.save()
		# Have the user follow themselves
		user_profile.follows.set([instance.profile.id])
		user_profile.save()

post_save.connect(create_profile, sender=User)

musker/forms.py
from django import forms
from .models import Meep, Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Profile Extras Form
class ProfilePicForm(forms.ModelForm):
	profile_image = forms.ImageField(label="Profile Picture")
	profile_bio = forms.CharField(label="Profile Bio", widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Profile Bio'}))
	homepage_link = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Website Link'}))
	facebook_link =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Facebook Link'}))
	instagram_link = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Instagram Link'}))
	linkedin_link =  forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Linkedin Link'}))
	
	class Meta:
		model = Profile
		fields = ('profile_image', 'profile_bio', 'homepage_link', 'facebook_link', 'instagram_link', 'linkedin_link', )

class MeepForm(forms.ModelForm):
	body = forms.CharField(required=True, 
		widget=forms.widgets.Textarea(
			attrs={
			"placeholder": "Enter Your Musker Meep!",
			"class":"form-control",
			}
			),
			label="",
		)

	class Meta:
		model = Meep
		exclude = ("user", "likes",)


class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

musker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Profile, Meep
from .forms import MeepForm, SignUpForm, ProfilePicForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

def home(request):
	if request.user.is_authenticated:
		form = MeepForm(request.POST or None)
		if request.method == "POST":
			if form.is_valid():
				meep = form.save(commit=False)
				meep.user = request.user
				meep.save()
				messages.success(request, ("Your Meep Has Been Posted!"))
				return redirect('home')
		
		meeps = Meep.objects.all().order_by("-created_at")
		return render(request, 'home.html', {"meeps":meeps, "form":form})
	else:
		meeps = Meep.objects.all().order_by("-created_at")
		return render(request, 'home.html', {"meeps":meeps})


def profile_list(request):
	if request.user.is_authenticated:
		profiles = Profile.objects.exclude(user=request.user)
		return render(request, 'profile_list.html', {"profiles":profiles})
	else:
		messages.success(request, ("You Must Be Logged In To View This Page..."))
		return redirect('home')

def unfollow(request, pk):
	if request.user.is_authenticated:
		# Get the profile to unfollow
		profile = Profile.objects.get(user_id=pk)
		# Unfollow the user
		request.user.profile.follows.remove(profile)
		# Save our profile
		request.user.profile.save()

		# Return message
		messages.success(request, (f"You Have Successfully Unfollowed {profile.user.username}"))
		return redirect(request.META.get("HTTP_REFERER"))

	else:
		messages.success(request, ("You Must Be Logged In To View This Page..."))
		return redirect('home')

def follow(request, pk):
	if request.user.is_authenticated:
		# Get the profile to unfollow
		profile = Profile.objects.get(user_id=pk)
		# Unfollow the user
		request.user.profile.follows.add(profile)
		# Save our profile
		request.user.profile.save()

		# Return message
		messages.success(request, (f"You Have Successfully Followed {profile.user.username}"))
		return redirect(request.META.get("HTTP_REFERER"))

	else:
		messages.success(request, ("You Must Be Logged In To View This Page..."))
		return redirect('home')




def profile(request, pk):
	if request.user.is_authenticated:
		profile = Profile.objects.get(user_id=pk)
		meeps = Meep.objects.filter(user_id=pk).order_by("-created_at")

		# Post Form logic
		if request.method == "POST":
			# Get current user
			current_user_profile = request.user.profile
			# Get form data
			action = request.POST['follow']
			# Decide to follow or unfollow
			if action == "unfollow":
				current_user_profile.follows.remove(profile)
			elif action == "follow":
				current_user_profile.follows.add(profile)
			# Save the profile
			current_user_profile.save()



		return render(request, "profile.html", {"profile":profile, "meeps":meeps})
	else:
		messages.success(request, ("You Must Be Logged In To View This Page..."))
		return redirect('home')		

def followers(request, pk):
	if request.user.is_authenticated:
		if request.user.id == pk:
			profiles = Profile.objects.get(user_id=pk)
			return render(request, 'followers.html', {"profiles":profiles})
		else:
			messages.success(request, ("That's Not Your Profile Page..."))
			return redirect('home')	
	else:
		messages.success(request, ("You Must Be Logged In To View This Page..."))
		return redirect('home')


def follows(request, pk):
	if request.user.is_authenticated:
		if request.user.id == pk:
			profiles = Profile.objects.get(user_id=pk)
			return render(request, 'follows.html', {"profiles":profiles})
		else:
			messages.success(request, ("That's Not Your Profile Page..."))
			return redirect('home')	
	else:
		messages.success(request, ("You Must Be Logged In To View This Page..."))
		return redirect('home')



def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, ("You Have Been Logged In!  Get MEEPING!"))
			return redirect('/')
		else:
			messages.success(request, ("There was an error logging in. Please Try Again..."))
			return redirect('login')

	else:
		return render(request, "login.html", {})


def logout_user(request):
	logout(request)
	messages.success(request, ("You Have Been Logged Out. Sorry to Meep You Go..."))
	return redirect('/')

def register_user(request):
	form = SignUpForm()
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			# first_name = form.cleaned_data['first_name']
			# second_name = form.cleaned_data['second_name']
			# email = form.cleaned_data['email']
			# Log in user
			user = authenticate(username=username, password=password)
			login(request,user)
			messages.success(request, ("You have successfully registered! Welcome!"))
			return redirect('home')
	
	return render(request, "register.html", {'form':form})


def update_user(request):
	if request.user.is_authenticated:
		current_user = User.objects.get(id=request.user.id)
		profile_user = Profile.objects.get(user__id=request.user.id)
		# Get Forms
		user_form = SignUpForm(request.POST or None, request.FILES or None, instance=current_user)
		profile_form = ProfilePicForm(request.POST or None, request.FILES or None, instance=profile_user)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()

			login(request, current_user)
			messages.success(request, ("Your Profile Has Been Updated!"))
			return redirect('home')

		return render(request, "update_user.html", {'user_form':user_form, 'profile_form':profile_form})
	else:
		messages.success(request, ("You Must Be Logged In To View That Page..."))
		return redirect('home')
	
def meep_like(request, pk):
	if request.user.is_authenticated:
		meep = get_object_or_404(Meep, id=pk)
		if meep.likes.filter(id=request.user.id):
			meep.likes.remove(request.user)
		else:
			meep.likes.add(request.user)
		
		return redirect(request.META.get("HTTP_REFERER"))




	else:
		messages.success(request, ("You Must Be Logged In To View That Page..."))
		return redirect('home')


def meep_show(request, pk):
	meep = get_object_or_404(Meep, id=pk)
	if meep:
		return render(request, "show_meep.html", {'meep':meep})
	else:
		messages.success(request, ("That Meep Does Not Exist..."))
		return redirect('home')		


def delete_meep(request, pk):
	if request.user.is_authenticated:
		meep = get_object_or_404(Meep, id=pk)
		# Check to see if you own the meep
		if request.user.username == meep.user.username:
			# Delete The Meep
			meep.delete()
			
			messages.success(request, ("The Meep Has Been Deleted!"))
			return redirect(request.META.get("HTTP_REFERER"))	
		else:
			messages.success(request, ("You Don't Own That Meep!!"))
			return redirect('home')

	else:
		messages.success(request, ("Please Log In To Continue..."))
		return redirect(request.META.get("HTTP_REFERER"))


def edit_meep(request,pk):
	if request.user.is_authenticated:
		# Grab The Meep!
		meep = get_object_or_404(Meep, id=pk)

		# Check to see if you own the meep
		if request.user.username == meep.user.username:
			
			form = MeepForm(request.POST or None, instance=meep)
			if request.method == "POST":
				if form.is_valid():
					meep = form.save(commit=False)
					meep.user = request.user
					meep.save()
					messages.success(request, ("Your Meep Has Been Updated!"))
					return redirect('home')
			else:
				return render(request, "edit_meep.html", {'form':form, 'meep':meep})
	
		else:
			messages.success(request, ("You Don't Own That Meep!!"))
			return redirect('home')

	else:
		messages.success(request, ("Please Log In To Continue..."))
		return redirect('home')



def search(request):
	if request.method == "POST":
		# Grab the form field input
		search = request.POST['search']
		# Search the database
		searched = Meep.objects.filter(body__contains = search)

		return render(request, 'search.html', {'search':search, 'searched':searched})
	else:
		return render(request, 'search.html', {})

musker/templates/followers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<h1>{{ request.user.username }}'s Followers</h1>
<br/>

{% if profiles %}

	{% for profile in profiles.followed_by.all %}

		<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      {% if profile.profile_image %}
      <img src="{{ profile.profile_image.url }}" width=200 height=200 class="img-fluid rounded-start" alt="{{profile.user.username}}">
      {% else %}

      <img src="{% static 'images/default_profile_pic.png' %}" class="img-fluid rounded-start" alt="Profile Image">

      {% endif %}

      
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ profile.user.username }}
        {% if profile in profiles.follows.all %}
<a href="{% url 'musker:unfollow' profile.user.id %}">
<i class="fa fa-user-minus small" style="color:gray"></i>
  </a>
           {% else %}
 <a href="{% url 'musker:follow' profile.user.id %}">
 <i class="fa fa-user-plus small" style="color:gray"></i>
  </a>
           {% endif %}

        </h5>
        <p class="card-text"><a href="{% url 'profile' profile.user.id %}">@{{ profile.user.username|lower }}</a></p>
        <br/><br/>
        <p class="card-text"><small class="text-muted">Last Updated: {{ profile.date_modified }}</small></p>
      </div>
    </div>
  </div>
</div>
<br/><br/>



	{% endfor %}

{% endif %}


{% endblock %}

musker/templates/follows.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<h1>{{ request.user.username }} is Following...</h1>
<br/>

{% if profiles %}

	{% for profile in profiles.follows.all %}

		<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      {% if profile.profile_image %}
      <img src="{{ profile.profile_image.url }}" width=200 height=200 class="img-fluid rounded-start" alt="{{profile.user.username}}">
      {% else %}

      <img src="{% static 'images/default_profile_pic.png' %}" class="img-fluid rounded-start" alt="Profile Image">

      {% endif %}

      
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ profile.user.username }}
        {% if profile in profiles.follows.all %}
<a href="{% url 'musker:unfollow' profile.user.id %}">
<i class="fa fa-user-minus small" style="color:gray"></i>
  </a>
           {% else %}
 <a href="{% url 'musker:follow' profile.user.id %}">
 <i class="fa fa-user-plus small" style="color:gray"></i>
  </a>
           {% endif %}

        </h5>
        <p class="card-text"><a href="{% url 'profile' profile.user.id %}">@{{ profile.user.username|lower }}</a></p>
        <br/><br/>
        <p class="card-text"><small class="text-muted">Last Updated: {{ profile.date_modified }}</small></p>
      </div>
    </div>
  </div>
</div>
<br/><br/>



	{% endfor %}

{% endif %}


{% endblock %}

musker/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


	<div class="container text-center">
		<div class="row">
			<div class="col-8">


	<h1>Meeps!</h1>
<br/>
	{% for meep in meeps %}
		<div class="alert alert-dark" role="alert">
<div class="container">
	<div class="row">
		<div class="col-1">
		  {% if meep.user.profile.profile_image %}
				<img src="{{ meep.user.profile.profile_image.url }}" width=50 height=50 class="rounded-circle" alt="{{ profile.user.username }}">

				{% else %}
				<img src="{% static 'images/default_profile_pic.png' %}" width=50 height=50 class="rounded-circle" alt="{{ profile.user.username }}">	
				{% endif %}
		</div>

		<div class="col-11">
		  {{ meep.body }}<br/>
		  <small class="text-muted">
		  	({{ meep.created_at}}) By 
		  	@{{ meep.user.username }}
		  	&nbsp;&nbsp;
		  	{{ meep.number_of_likes }}  

		  	{% if user in meep.likes.all %}
		  	  <a href="{% url 'musker:meep_like' meep.id %}">
	<i class="fa-solid fa-heart" style="color:red"></i></a>
		  	{% else %}
		  		<a href="{% url 'musker:meep_like' meep.id %}">
		  <i class="fa fa-heart-o" style="color:red"></i></a>
		  	{% endif %}
		  	&nbsp;&nbsp;
		  	<a href="{% url 'musker:meep_show' meep.id %}">
	<i class="fa-solid fa-share" style="color:gray"></i>
		  	</a>
		  	

		  </small>
		</div><br/><br/>
	
			</div>
		</div>
	</div>
	{% endfor %}

</div>

<div class="col-4">
				<br/><br/><br/>
{% if form %}
<form  method=POST>
	{% csrf_token %}
  	{{ form.as_p }}


  <button type="submit" class="btn btn-secondary">Post Meep!</button>
</form>
{% endif %}
</div>

{% endblock %}

musker/templates/login.html
{% extends 'base.html' %}
{% block content %}

{% if user.is_authenticated %}
<h1>You're Already Logged In!</h1>

{% else %}
<div class="col-md-6 offset-md-3">
<h1>Login</h1>
<br/>
<form method="POST" action="{% url 'musker:login' %}">
	{% csrf_token %}

  <div class="mb-3">
    
    <input type="text" class="form-control" name="username" placeholder="Enter Your Username">
    
  </div>
  <div class="mb-3">
    
    <input type="password" class="form-control" name="password" placeholder="Enter Your Password">
  </div>
  <br/>
  <button type="submit" class="btn btn-secondary">Submit</button>
</form>

</div>

{% endif %}
{% endblock %}

musker/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'musker:home' %}">Musker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <a class="nav-link" 
          href="{% url 'musker:profile_list' %}">Profile List</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" 
          href="{% url 'musker:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" 
          href="{% url 'musker:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" 
          href="{% url 'musker:login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" 
          href="{% url 'musker:search' %}">Search</a>
        </li>
        
        
      </ul>

      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-link navbar-brand">
            <a href="{% url 'musker:profile' request.user.id %}">
{% if user.profile.profile_image %}
<img src="{{ user.profile.profile_image.url }}" class="rounded-circle" width=30>
{% else %}
    <img src="{% static 'images/default_profile_pic.png' %}" class="img-fluid rounded-circle" alt="Profile Image" width=30>

{% endif %}
            </a>
            
          </li>
        </ul>
      {% endif %}

      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->

    </div>
  </div>
</nav>

musker/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if profile %}

	<div class="container text-center">
		<div class="row">
			<div class="col-8">
				<h1>{{ profile.user.username }}'s Profile</h1>
				<br/>
				{% if meeps %}
					{% for meep in meeps %}

			<div class="alert alert-dark" role="alert">
	<div class="container">
		<div class="row">
			<div class="col-1">
				{% if profile.profile_image %}
				<img src="{{ profile.profile_image.url }}" width=50 height=50 class="rounded-circle" alt="{{ profile.user.username }}">

				{% else %}
				<img src="{% static 'images/default_profile_pic.png' %}" width=50 height=50 class="rounded-circle" alt="{{ profile.user.username }}">	
				{% endif %}


			</div>

			<div class="col-11">
						  {{ meep.body }}<br/>
			  				<small class="text-muted">
			  					({{ meep.created_at}}) By 
			  					@{{ meep.user.username }}
			  		- {{ meep.number_of_likes }} Likes -
			  		
			  		{% if user in meep.likes.all %}
				  	  <a href="{% url 'musker:meep_like' meep.id %}"><i class="fa-solid fa-heart" style='color:red'></i></a>
				  	{% else %}
				  		<a href="{% url 'musker:meep_like' meep.id %}"><i class="fa fa-heart-o" style="color:red"></i></a>
				  	{% endif %}

				  	&nbsp;&nbsp;
<a href="{% url 'musker:meep_show' meep.id %}"><i class="fa-solid fa-share" style="color:gray"></i></a>
		  	

{% if request.user.username == profile.user.username %}
		  	&nbsp;&nbsp;
<a href="{% url 'musker:delete_meep' meep.id %}"><i class="fa fa-trash" style="color:gray"></i></a>
		&nbsp;&nbsp;
<a href="{% url 'edit_meep' meep.id %}"><i class="fa fa-edit" style="color:gray"></i></a>
{% endif %}
				  	


			  				</small>
						</div><br/><br/>
			</div>
		</div>
	</div>

					{% endfor %}
				{% endif %}
			</div>

			<div class="col-4">
				<br/><br/><br/>

				{% if profile.profile_image %}
				<img src="{{ profile.profile_image.url }}" class="rounded-circle">
				<br/><br/>
				{% endif %}

				{% if profile.homepage_link %}
	<a href="{{ profile.homepage_link }}" target="new">
				<i class="fa-solid fa-link" style="color:gray"></i></a>
				{% endif %}
				&nbsp;&nbsp;
				{% if profile.facebook_link %}
	<a href="{{ profile.facebook_link }}" target="new">
		<i class="fa-brands fa-facebook-f" style="color:gray"></i></a>
				{% endif %}
				&nbsp;&nbsp;
				{% if profile.instagram_link %}
	<a href="{{ profile.instagram_link }}" target="new">
		<i class="fa-brands fa-instagram" style="color:gray"></i></a>
				{% endif %}
				&nbsp;&nbsp;
				{% if profile.linkedin_link %}
	<a href="{{ profile.linkedin_link }}" target="new">
		<i class="fa-brands fa-linkedin-in" style="color:gray"></i></a>
				{% endif %}
<br/><br/>

{% if profile.profile_bio %}
	<p align="justify">
		{{profile.profile_bio }}
	</p>
{% endif %}


<br/><br/>
				<div class="card">
  <h5 class="card-header">Follows</h5>
  <div class="card-body">
    
    <p class="card-text">
    		{% for following in profile.follows.all %}
				<a href="{% url 'musker:profile' following.user.id %}">@{{ following }}</a> 
	<a href="{% url 'musker:unfollow' following.user.id %}">
	<i class="fa fa-user-minus small" style="color:gray"></i>
</a>
<br/>

			{% endfor %}

    </p>
    
  </div>
  <div class="card-footer text-end">
    <a href="{% url 'musker:follows' profile.user.id %}"
    class="btn btn-sm btn-outline-secondary">See All...</a>
  </div>
</div>
			
			

			<br/><br/>

			<div class="card">
  <h5 class="card-header">Followed By</h5>
  <div class="card-body">
    
    <p class="card-text">
    	{% for following in profile.followed_by.all|slice:3 %}
				<a href="{% url 'musker:profile' following.user.id %}">@{{ following }}</a>&nbsp;&nbsp;

				{% if following in profile.follows.all %}
				 <a href="{% url 'musker:unfollow' following.user.id %}">
	<i class="fa fa-user-minus small" style="color:gray"></i>
</a>
				 {% else %}
				 <a href="{% url 'musker:follow' following.user.id %}">
	<i class="fa fa-user-plus small" style="color:gray"></i>
</a>
				 {% endif %}


				<br/>
			{% endfor %}
			<br/>
			 

			

    </p>
    
  </div>
  <div class="card-footer text-end">
    <a href="{% url 'musker:followers' profile.user.id %}"
    class="btn btn-sm btn-outline-secondary">See All...</a>
  </div>
</div>
<br/>

<form method=POST>
{% csrf_token %}
{% if profile in user.profile.follows.all %}
 	<button class="btn btn-outline-danger" name="follow" value="unfollow" type="submit">
 		Unfollow @{{ profile.user.username|lower}}
 	</button>

{% else %}
	<button class="btn btn-outline-success" name="follow" value="follow" type="submit">
 		Follow @{{ profile.user.username|lower}}
 	</button>

{% endif %}

</form>
<br/>
	
	<!-- Check For Correct User -->
	{% if request.user.id == profile.user.id %}
		<a href="{% url 'musker:update_user' %}" class="btn btn-outline-secondary">Update Profile</a>
	{% endif %}
			</div>
		</div>
	</div>
{% endif %}

{% endblock %}